[DRAFT - DO NOT MERGE] Extracted destination section to its own component
EndzoneSoftware/CT-patternlib pull request #3
Opened 2020-11-23 19:01 UTC by pedroyan

https://drive.google.com/file/d/1TH7-uKKCTKGVKnF-aSffGG5rkzBDKGVs/view?usp=sharing

2020-11-24 17:00 UTC, pedroyan commented
@barryokane I've coded a mechanism to detect if the JS is running in the patternlib and if so, it will mock an API call for better visualization of the entire component

2020-11-25 12:43 UTC, barryokane approved these changes
Nice work.

Patternlib supports separate json files for test data (both globally and for each specific pattern) - so I move your test data.  Otherwise all good.

2020-11-25 12:43 UTC, barryokane commented on source/_patterns/03-organisms/referrer-destination-renderer.twig
> +{% include "molecules-referrer-destination-form" with {
Patternlib supports json files for test data (both globally and per pattern file). So I move the test model for this to a separate .json file.

2020-11-25 12:45 UTC, barryokane commented
Wait - I'm getting JS errors...

2020-11-25 13:01 UTC, barryokane requested changes
I really like the idea of mocking the API call in the pattern.

However, as ui-scripts.js is copied exactly as is to the live site, that means we'll have a bunch of code that is not relevant to live.  And that file is complex/messy enough as it is (and it is not currently minified).

So, my preference would be to move the mock to a separate js file that is only used on the patternlib

2020-11-25 14:33 UTC, pedroyan commented on source/js/ui-scripts.js
> +function validateGroup(){
Leave this function here, but don't modify it with mock stuff.

Instead, intercept the onClick function using jQuery and execute the mock when running JS inside the patternlib

2022-08-27 18:52 UTC, closed without merging